// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02nM62mvgzZ39FWU2wTJmv8RquqoJ4Eg',
    appId: '1:973699067485:web:5d8c787d86f7c76ef467b4',
    messagingSenderId: '973699067485',
    projectId: 'croai-cc-001-prod',
    authDomain: 'croai-cc-001-prod.firebaseapp.com',
    storageBucket: 'croai-cc-001-prod.firebasestorage.app',
    measurementId: 'G-BLM0YK158R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXW1WvvUWGP4HQzDzeuHoZIE1Ati3UX3c',
    appId: '1:973699067485:android:ea214692e5543ceaf467b4',
    messagingSenderId: '973699067485',
    projectId: 'croai-cc-001-prod',
    storageBucket: 'croai-cc-001-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUHV8jfbHahiF34BSHTI7ocRsInmVk6I',
    appId: '1:973699067485:ios:fb8beb91b127279ff467b4',
    messagingSenderId: '973699067485',
    projectId: 'croai-cc-001-prod',
    storageBucket: 'croai-cc-001-prod.firebasestorage.app',
    iosClientId: '973699067485-ap13buaaord3qh5mdh0ohlecqhtecnde.apps.googleusercontent.com',
    iosBundleId: 'com.croai.cc-001',
  );
}
